/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutflowRouteImport } from './routes/outflow'
import { Route as InflowRouteImport } from './routes/inflow'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const OutflowRoute = OutflowRouteImport.update({
  id: '/outflow',
  path: '/outflow',
  getParentRoute: () => rootRouteImport,
} as any)
const InflowRoute = InflowRouteImport.update({
  id: '/inflow',
  path: '/inflow',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inflow': typeof InflowRoute
  '/outflow': typeof OutflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inflow': typeof InflowRoute
  '/outflow': typeof OutflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inflow': typeof InflowRoute
  '/outflow': typeof OutflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/inflow' | '/outflow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/inflow' | '/outflow'
  id: '__root__' | '/' | '/dashboard' | '/inflow' | '/outflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InflowRoute: typeof InflowRoute
  OutflowRoute: typeof OutflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/outflow': {
      id: '/outflow'
      path: '/outflow'
      fullPath: '/outflow'
      preLoaderRoute: typeof OutflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inflow': {
      id: '/inflow'
      path: '/inflow'
      fullPath: '/inflow'
      preLoaderRoute: typeof InflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InflowRoute: InflowRoute,
  OutflowRoute: OutflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
